# Generated by Django 4.1.7 on 2023-07-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0002_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Jammu', 'Jammu'), ('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Haryana', 'Haryana'), ('Chennai', 'Chennai'), ('Rajasthan', 'Rajasthan')], max_length=100),
        ),
    ]
